/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
/* Header for class jniActivity_DotMatrix */

#ifndef _Included_jniActivity_DotMatrix
#define _Included_jniActivity_DotMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniActivity_DotMatrix
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_DotMatrix_Open
  (JNIEnv *, jobject);

/*
 * Class:     jniActivity_DotMatrix
 * Method:    Control
 * Signature: (I)Z
 */
JNIEXPORT jint JNICALL Java_jniActivity_DotMatrix_Control
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jniActivity_DotMatrix
 * Method:    Close
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_DotMatrix_Close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
