/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
/* Header for class jniActivity_DipSW */

#ifndef _Included_jniActivity_DipSW
#define _Included_jniActivity_DipSW
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniActivity_DipSW
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_DipSW_Open
  (JNIEnv *, jobject);

/*
 * Class:     jniActivity_DipSW
 * Method:    Close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_DipSW_Close
  (JNIEnv *, jobject);

/*
 * Class:     jniActivity_DipSW
 * Method:    GetValue
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jniActivity_DipSW_GetValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
