/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
/* Header for class jniActivity_LED */

#ifndef _Included_jniActivity_LED
#define _Included_jniActivity_LED
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniActivity_LED
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_LED_Open
  (JNIEnv *, jobject);

/*
 * Class:     jniActivity_LED
 * Method:    TurnOn
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_LED_TurnOn
  (JNIEnv *, jobject, jint);

/*
 * Class:     jniActivity_LED
 * Method:    TurnOffAll
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_LED_TurnOffAll
  (JNIEnv *, jobject);

/*
 * Class:     jniActivity_LED
 * Method:    Close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_LED_Close
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
