/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
/* Header for class jniActivity_FullColor */

#ifndef _Included_jniActivity_FullColor
#define _Included_jniActivity_FullColor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniActivity_FullColor
 * Method:    Open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_FullColor_Open
        (JNIEnv *, jobject);

/*
 * Class:     jniActivity_FullColor
 * Method:    Control
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_jniActivity_FullColor_Control
        (JNIEnv *, jobject, jint, jint, jint, jint);

/*
 * Class:     jniActivity_FullColor
 * Method:    Close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_FullColor_Close
        (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
