/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
/* Header for class jniActivity_Segment */

#ifndef _Included_jniActivity_Segment
#define _Included_jniActivity_Segment
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniActivity_Segment
 * Method:    SegmentControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_Segment_SegmentControl
  (JNIEnv *, jobject, jint);

/*
 * Class:     jniActivity_Segment
 * Method:    SegmentIOControl
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_Segment_SegmentIOControl
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
