/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
#include <fcntl.h>
#include <errno.h>
/* Header for class jniActivity_Image */

#ifndef _Included_jniActivity_Image
#define _Included_jniActivity_Image
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jniActivity_Image
 * Method:    open
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_Image_open
  (JNIEnv *, jobject);

/*
 * Class:     jniActivity_Image
 * Method:    Control
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_jniActivity_Image_Control
  (JNIEnv *, jobject, jintArray);

/*
 * Class:     jniActivity_Image
 * Method:    close
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_jniActivity_Image_close
  (JNIEnv *, jobject);

JNIEXPORT void JNICALL Java_jniActivity_Image_clear
        (JNIEnv *, jobject);
#ifdef __cplusplus
}
#endif
#endif
